linters:
  enable-all: true

linters-settings:
  gci:
    sections:
      - standard
      - default
      - prefix(github.com/devemio/docker-color-output)
  varnamelen:
    ignore-names: [ i, in, j, m, sb, tt, v ]
  depguard:
    rules:
      main:
        allow:
          - $gostd # matches all of go's standard library
          - github.com/devemio/docker-color-output