linters:
  enable-all: true
  disable:
    - depguard

linters-settings:
  gci:
    sections:
      - standard
      - default
      - prefix(github.com/devemio/docker-color-output)
  varnamelen:
    ignore-names:
      - i, j, fn, in, tt
      - x, sb

issues:
  exclude-rules:
    - path: '(.+)_test\.go'
      linters:
        - funlen
        - exhaustruct